"""change winningPercentage column to drivers

Revision ID: 05309b0041be
Revises: 89d9cdf9e2b6
Create Date: 2026-08-17 00:22:35.531309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05309b0041be'
down_revision: Union[str, Sequence[str], None] = '89d9cdf9e2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('winningPercentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'winningPercentage')
    # ### end Alembic commands ###
