"""add avg start and end positions column to drivers

Revision ID: 058c57165dd6
Revises: d9c78b1ca87b
Create Date: 2026-08-17 23:02:28.441416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058c57165dd6'
down_revision: Union[str, Sequence[str], None] = 'd9c78b1ca87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('avgStartPosition', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('driver', sa.Column('avgEndPosition', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'avgEndPosition')
    op.drop_column('driver', 'avgStartPosition')
    # ### end Alembic commands ###
