"""change hatTricks counter in Driver

Revision ID: 28984a48e9b4
Revises: edc1684a2330
Create Date: 2026-08-17 20:36:15.743027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28984a48e9b4'
down_revision: Union[str, Sequence[str], None] = 'edc1684a2330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('hatTricks', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'hatTricks')
    # ### end Alembic commands ###
