"""add nationality to drivers

Revision ID: 3dd3c79183df
Revises: 84c7a537d3b6
Create Date: 2026-08-16 04:14:14.790598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd3c79183df'
down_revision: Union[str, Sequence[str], None] = '84c7a537d3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('nationality', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'nationality')
    # ### end Alembic commands ###
