"""add race's circut name

Revision ID: 4b23ef751f86
Revises: 
Create Date: 2026-08-15 00:03:15.531193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b23ef751f86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'driver',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('driverId', sa.String(length=30), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('lastName', sa.String(length=30), nullable=False),
        sa.Column('driverNumber', sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'race',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('season', sa.String(length=4), nullable=False),
        sa.Column('raceName', sa.String(length=30), nullable=False),
        sa.Column('date', sa.String(length=30), nullable=False),
        sa.Column('circuitName', sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race')
    op.drop_table('driver')
    # ### end Alembic commands ###
