"""add race's circut name

Revision ID: 53eb0d45164c
Revises: 4b23ef751f86
Create Date: 2026-08-15 00:17:51.818156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53eb0d45164c'
down_revision: Union[str, Sequence[str], None] = '4b23ef751f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race', 'circuitName',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race', 'circuitName',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
