"""change winningPercentage to float

Revision ID: 9a7cef8a2395
Revises: 05309b0041be
Create Date: 2026-08-17 00:42:13.055693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7cef8a2395'
down_revision: Union[str, Sequence[str], None] = '05309b0041be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver', 'winningPercentage',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver', 'winningPercentage',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
