"""drop length column from races

Revision ID: c7d98b618788
Revises: 058c57165dd6
Create Date: 2026-08-20 23:14:23.394340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d98b618788'
down_revision: Union[str, Sequence[str], None] = '058c57165dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'lenght')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('lenght', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
