"""add locality, country and lenght to races

Revision ID: cf7170960d20
Revises: 3dd3c79183df
Create Date: 2026-08-16 20:01:20.863094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7170960d20'
down_revision: Union[str, Sequence[str], None] = '3dd3c79183df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('locality', sa.String(length=50), nullable=True))
    op.add_column('race', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('race', sa.Column('lenght', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'lenght')
    op.drop_column('race', 'country')
    op.drop_column('race', 'locality')
    # ### end Alembic commands ###
