"""change nullability to columms

Revision ID: d180cdead844
Revises: cf7170960d20
Create Date: 2026-08-16 23:31:50.093399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd180cdead844'
down_revision: Union[str, Sequence[str], None] = 'cf7170960d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver', 'nationality',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('race', 'locality',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('race', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('race', 'lenght',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race', 'lenght',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('race', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('race', 'locality',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('driver', 'nationality',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
