"""add podiums column to driver

Revision ID: d9c78b1ca87b
Revises: 677b4ed55002
Create Date: 2026-08-17 22:42:19.086383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c78b1ca87b'
down_revision: Union[str, Sequence[str], None] = '677b4ed55002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('podiums', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'podiums')
    # ### end Alembic commands ###
